ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER CONSUMER IDENTIFIED BY "123456";

GRANT CREATE SESSION TO CONSUMER;
ALTER USER CONSUMER quota unlimited ON USERS;

CREATE SEQUENCE consumer.consumer_seq INCREMENT BY 1;

CREATE TABLE consumer.paciente (
	CODIGO INTEGER NOT NULL,
	NOME VARCHAR2(100) NOT NULL,
	CPF VARCHAR2(11) NOT NULL,
	DATA_NASCIMENTO TIMESTAMP NOT NULL,
	CONSTRAINT PACIENTE_PK PRIMARY KEY (CODIGO)
);

ALTER SESSION SET "_ORACLE_SCRIPT"=false;